"use strict";

export const CITY_TZ = {
  "Алматы": "Asia/Almaty",
  "Архангельск": "Europe/Moscow",
  "Барнаул": "Asia/Barnaul",
  "Белгород": "Europe/Moscow",
  "Владивосток": "Asia/Vladivostok",
  "Владикавказ": "Europe/Moscow",
  "Владимир": "Europe/Moscow",
  "Волгоград": "Europe/Volgograd",
  "Воронеж": "Europe/Moscow",
  "Екатеринбург": "Asia/Yekaterinburg",
  "Иваново": "Europe/Moscow",
  "Ижевск": "Europe/Samara",
  "Иркутск": "Asia/Irkutsk",
  "Казань": "Europe/Moscow",
  "Калининград": "Europe/Kaliningrad",
  "Калуга": "Europe/Moscow",
  "Кемерово": "Asia/Novokuznetsk",
  "Киров": "Europe/Kirov",
  "Кострома": "Europe/Moscow",
  "Краснодар": "Europe/Moscow",
  "Красноярск": "Asia/Krasnoyarsk",
  "Курск": "Europe/Moscow",
  "Липецк": "Europe/Moscow",
  "Магнитогорск": "Asia/Yekaterinburg",
  "Москва": "Europe/Moscow",
  "Набережные Челны": "Europe/Moscow",
  "Нижний Новгород": "Europe/Moscow",
  "Новокузнецк": "Asia/Novokuznetsk",
  "Новороссийск": "Europe/Moscow",
  "Новосибирск": "Asia/Novosibirsk",
  "Омск": "Asia/Omsk",
  "Орел": "Europe/Moscow",
  "Орёл": "Europe/Moscow",
  "Оренбург": "Asia/Yekaterinburg",
  "Пенза": "Europe/Moscow",
  "Пермь": "Asia/Yekaterinburg",
  "Петрозаводск": "Europe/Moscow",
  "Псков": "Europe/Moscow",
  "Ростов-на-Дону": "Europe/Moscow",
  "Рязань": "Europe/Moscow",
  "Самара": "Europe/Samara",
  "Санкт-Петербург": "Europe/Moscow",
  "Саранск": "Europe/Moscow",
  "Саратов": "Europe/Saratov",
  "Смоленск": "Europe/Moscow",
  "Ставрополь": "Europe/Moscow",
  "Сургут": "Asia/Yekaterinburg",
  "Тверь": "Europe/Moscow",
  "Тольятти": "Europe/Samara",
  "Тула": "Europe/Moscow",
  "Тюмень": "Asia/Yekaterinburg",
  "Ульяновск": "Europe/Ulyanovsk",
  "Уфа": "Asia/Yekaterinburg",
  "Хабаровск": "Asia/Vladivostok",
  "Челябинск": "Asia/Yekaterinburg",
  "Череповец": "Europe/Moscow",
  "Ярославль": "Europe/Moscow"
};

export const CITY_TZ_LOOKUP = Object.fromEntries(
  Object.entries(CITY_TZ).map(([city, tz]) => [city.toLowerCase(), tz])
);

